# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 13:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.CharField(blank=True, max_length=200, null=True)),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('easy_pool', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('medium_pool', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('hard_pool', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('obj', models.CharField(blank=True, max_length=200, null=True)),
                ('target_image', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_id', models.CharField(blank=True, max_length=100, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assignment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('hit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('game_id', models.CharField(blank=True, max_length=100, null=True)),
                ('target_image', models.CharField(blank=True, max_length=100, null=True)),
                ('final_image_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='fc7_sorted',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='human_sorted',
        ),
        migrations.AddField(
            model_name='gameround',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameround',
            name='history',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='socket_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
