# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0004_auto_20170502_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageranking',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
