# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0006_auto_20170502_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagepool',
            name='is_active',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imageranking',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
    ]
