# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-07 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0007_auto_20170502_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imageranking',
            name='task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
